### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by raphaelcosta** [StanHutcheon/AuthGrabber#3]
./authGrabber.rb:63:in `parse': undefined method`[]' for nil:NilClass (NoMethodError)
    from ./authGrabber.rb:35:in `receive_binary_data'
    from /home/ec2-user/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/em/protocols/linetext2.rb:94:in`receive_data'
    from /home/ec2-user/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /home/ec2-user/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from ./authGrabber.rb:73:in `<main>'

**Comment by rops** [comment]
I get this one:

Request cached, writing to auths/acehosts2.txt
./authGrabber.rb:40:in `unbind': undefined method`close' for nil:NilClass (NoMethodError)
    from /home/daniele/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:1417:in `event_callback'
    from /home/daniele/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /home/daniele/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from ./authGrabber.rb:73:in`<main>'

**Comment by StanHutcheon** [comment]
AuthGrabber does spew out an error when auth data is cached, check acehosts0.txt (or whatever one it cached to)

**Comment by dionysius** [comment]
@rops please check #8 your trace is different so maybe also check my suggestion there - maybe this will fix it.
@raphaelcosta @StanTheRipper confirm, after fixing #8 I get this error trace, BUT acehostsX.txt has content
