### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rops** [StanHutcheon/AuthGrabber#4]
after running rvmsudo ./cache.sh

Request cached, writing to auths/acehosts2.txt
./authGrabber.rb:40:in `unbind': undefined method`close' for nil:NilClass (NoMethodError)
    from /home/daniele/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:1417:in `event_callback'
    from /home/daniele/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /home/daniele/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from ./authGrabber.rb:73:in`<main>'

**Comment by rops** [comment]
And one more thing...I tried to dump the traffic between the server and the iphone 4s...the iphone ask for guzzoni.apple.com but the server answers with 0.0.0.0...isn't it wrong??

**Comment by StanHutcheon** [comment]
you can change 0.0.0.0 to your IP address if you wish, it does make a difference if you're running a multi-ip server, check you have nothing running on ports 53 and 443 and finally, check your acehosts .txt files, eventmachine does spew out errors when auth data is cached.

**Comment by rops** [comment]
you are right..acehosts contains the datas although the errors...about the dns, I realized that dnsmasq is based on /etc/hosts so I added the right dns entry to that file and it worked.
