### ISSUE TITLE
Authgrabber Load Error Ubuntu 11.10

### ISSUE THREAD

**Issue by mamismo27** [StanHutcheon/AuthGrabber#5]
Everytime I Try to open Authgrabber with
sudo ruby authgrabber.rb > OUTPUT.txt
I get ruby: No such file or directory -- authgrabber.rb (LoadError)
How do I fix this.

**Comment by StanHutcheon** [comment]
Make sure you're in the AuthGrabber directory

**Comment by mamismo27** [comment]
thanks
